name: run-code
# on: [push]
on:
  workflow_dispatch:
jobs:
  compile-run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: compile
        run: g++ -O3 MonteCarlo/MonteCarlo2.cpp
      - name: run
        run: ./a.out
